/* USER CODE BEGIN Header */
/**
 * @file custom_stm.h
 * @brief Header for custom_stm.c module.
 */
/*
  ******************************************************************************
  * File Name          : App/custom_stm.h
  * Description        : Header for custom_stm.c module.
  *
  ******************************************************************************
  * @attention
  *
  * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
  * All rights reserved.</center></h2>
  *
  * This software component is licensed by ST under Ultimate Liberty license
  * SLA0044, the "License"; You may not use this file except in compliance with
  * the License. You may obtain a copy of the License at:
  *                             www.st.com/SLA0044
  *
 ******************************************************************************
 */
/* USER CODE END Header */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __CUSTOM_STM_H
#define __CUSTOM_STM_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include <stdint.h>
#include "ble_types.h"
/* USER CODE END Includes */

/* Exported types ------------------------------------------------------------*/
typedef enum
{
  CUSTOM_STM_CLOCK_DATETIME,
  CUSTOM_STM_ALARM1_TIME,
  CUSTOM_STM_ALARM1_STATUS,
  CUSTOM_STM_ALARM2_TIME,
  CUSTOM_STM_ALARM2_STATUS,
  CUSTOM_STM_ALARM3_TIME,
  CUSTOM_STM_ALARM3_STATUS,
  CUSTOM_STM_ALARM4_TIME,
  CUSTOM_STM_ALARM4_STATUS,
  CUSTOM_STM_ALARM5_TIME,
  CUSTOM_STM_ALARM5_STATUS,
  CUSTOM_STM_ALARM6_TIME,
  CUSTOM_STM_ALARM6_STATUS,
  CUSTOM_STM_ALARM7_TIME,
  CUSTOM_STM_ALARM7_STATUS,
  CUSTOM_STM_ALARM8_TIME,
  CUSTOM_STM_ALARM8_STATUS,
  CUSTOM_STM_ALARM9_TIME,
  CUSTOM_STM_ALARM9_STATUS,
  CUSTOM_STM_ALARM10_TIME,
  CUSTOM_STM_ALARM10_STATUS,
  CUSTOM_STM_STOPWATCH_TIME_S,
  CUSTOM_STM_STOPWATCH_STATUS,
  CUSTOM_STM_TIMER_TIME_S,
  CUSTOM_STM_TIMER_SET_TIME_S,
  CUSTOM_STM_TIMER_STATUS,
  CUSTOM_STM_SETTINGS_LED_BLINK_INTERVAL_MS,
  CUSTOM_STM_SETTINGS_TIME_DISPLAY_DURATION_MS,
  CUSTOM_STM_SETTINGS_DATE_DISPLAY_DURATION_MS,
  CUSTOM_STM_SETTINGS_ALARM_RINGING_DURATION_MS,
  CUSTOM_STM_SETTINGS_TIMER_RINGING_DURATION_MS,
  CUSTOM_STM_SETTINGS_DATE_FORMAT,
  CUSTOM_STM_RTC_CALIBRATION_CALP,
  CUSTOM_STM_RTC_CALIBRATION_CALM
} Custom_STM_Char_Opcode_t;

typedef enum
{
  CUSTOM_STM_BOOT_REQUEST_EVT,
  CUSTOM_STM_CLOCK_DATETIME_READ_EVT,
  CUSTOM_STM_CLOCK_DATETIME_WRITE_EVT,
  CUSTOM_STM_CLOCK_DATETIME_NOTIFY_ENABLED_EVT,
  CUSTOM_STM_CLOCK_DATETIME_NOTIFY_DISABLED_EVT,
  CUSTOM_STM_ALARM1_TIME_READ_EVT,
  CUSTOM_STM_ALARM1_TIME_WRITE_EVT,
  CUSTOM_STM_ALARM1_STATUS_READ_EVT,
  CUSTOM_STM_ALARM1_STATUS_WRITE_EVT,
  CUSTOM_STM_ALARM2_TIME_READ_EVT,
  CUSTOM_STM_ALARM2_TIME_WRITE_EVT,
  CUSTOM_STM_ALARM2_STATUS_READ_EVT,
  CUSTOM_STM_ALARM2_STATUS_WRITE_EVT,
  CUSTOM_STM_ALARM3_TIME_READ_EVT,
  CUSTOM_STM_ALARM3_TIME_WRITE_EVT,
  CUSTOM_STM_ALARM3_STATUS_READ_EVT,
  CUSTOM_STM_ALARM3_STATUS_WRITE_EVT,
  CUSTOM_STM_ALARM4_TIME_READ_EVT,
  CUSTOM_STM_ALARM4_TIME_WRITE_EVT,
  CUSTOM_STM_ALARM4_STATUS_READ_EVT,
  CUSTOM_STM_ALARM4_STATUS_WRITE_EVT,
  CUSTOM_STM_ALARM5_TIME_READ_EVT,
  CUSTOM_STM_ALARM5_TIME_WRITE_EVT,
  CUSTOM_STM_ALARM5_STATUS_READ_EVT,
  CUSTOM_STM_ALARM5_STATUS_WRITE_EVT,
  CUSTOM_STM_ALARM6_TIME_READ_EVT,
  CUSTOM_STM_ALARM6_TIME_WRITE_EVT,
  CUSTOM_STM_ALARM6_STATUS_READ_EVT,
  CUSTOM_STM_ALARM6_STATUS_WRITE_EVT,
  CUSTOM_STM_ALARM7_TIME_READ_EVT,
  CUSTOM_STM_ALARM7_TIME_WRITE_EVT,
  CUSTOM_STM_ALARM7_STATUS_READ_EVT,
  CUSTOM_STM_ALARM7_STATUS_WRITE_EVT,
  CUSTOM_STM_ALARM8_TIME_READ_EVT,
  CUSTOM_STM_ALARM8_TIME_WRITE_EVT,
  CUSTOM_STM_ALARM8_STATUS_READ_EVT,
  CUSTOM_STM_ALARM8_STATUS_WRITE_EVT,
  CUSTOM_STM_ALARM9_TIME_READ_EVT,
  CUSTOM_STM_ALARM9_TIME_WRITE_EVT,
  CUSTOM_STM_ALARM9_STATUS_READ_EVT,
  CUSTOM_STM_ALARM9_STATUS_WRITE_EVT,
  CUSTOM_STM_ALARM10_TIME_READ_EVT,
  CUSTOM_STM_ALARM10_TIME_WRITE_EVT,
  CUSTOM_STM_ALARM10_STATUS_READ_EVT,
  CUSTOM_STM_ALARM10_STATUS_WRITE_EVT,
  CUSTOM_STM_STOPWATCH_TIME_S_READ_EVT,
  CUSTOM_STM_STOPWATCH_TIME_S_NOTIFY_ENABLED_EVT,
  CUSTOM_STM_STOPWATCH_TIME_S_NOTIFY_DISABLED_EVT,
  CUSTOM_STM_STOPWATCH_STATUS_READ_EVT,
  CUSTOM_STM_STOPWATCH_STATUS_WRITE_EVT,
  CUSTOM_STM_TIMER_TIME_S_READ_EVT,
  CUSTOM_STM_TIMER_TIME_S_NOTIFY_ENABLED_EVT,
  CUSTOM_STM_TIMER_TIME_S_NOTIFY_DISABLED_EVT,
  CUSTOM_STM_TIMER_SET_TIME_S_WRITE_EVT,
  CUSTOM_STM_TIMER_STATUS_READ_EVT,
  CUSTOM_STM_TIMER_STATUS_WRITE_EVT,
  CUSTOM_STM_TIMER_STATUS_NOTIFY_ENABLED_EVT,
  CUSTOM_STM_TIMER_STATUS_NOTIFY_DISABLED_EVT,
  CUSTOM_STM_SETTINGS_LED_BLINK_INTERVAL_MS_READ_EVT,
  CUSTOM_STM_SETTINGS_LED_BLINK_INTERVAL_MS_WRITE_EVT,
  CUSTOM_STM_SETTINGS_TIME_DISPLAY_DURATION_MS_READ_EVT,
  CUSTOM_STM_SETTINGS_TIME_DISPLAY_DURATION_MS_WRITE_EVT,
  CUSTOM_STM_SETTINGS_DATE_DISPLAY_DURATION_MS_READ_EVT,
  CUSTOM_STM_SETTINGS_DATE_DISPLAY_DURATION_MS_WRITE_EVT,
  CUSTOM_STM_SETTINGS_ALARM_RINGING_DURATION_MS_READ_EVT,
  CUSTOM_STM_SETTINGS_ALARM_RINGING_DURATION_MS_WRITE_EVT,
  CUSTOM_STM_SETTINGS_TIMER_RINGING_DURATION_MS_READ_EVT,
  CUSTOM_STM_SETTINGS_TIMER_RINGING_DURATION_MS_WRITE_EVT,
  CUSTOM_STM_SETTINGS_DATE_FORMAT_READ_EVT,
  CUSTOM_STM_SETTINGS_DATE_FORMAT_WRITE_EVT,
  CUSTOM_STM_RTC_CALIBRATION_CALP_READ_EVT,
  CUSTOM_STM_RTC_CALIBRATION_CALP_WRITE_EVT,
  CUSTOM_STM_RTC_CALIBRATION_CALM_READ_EVT,
  CUSTOM_STM_RTC_CALIBRATION_CALM_WRITE_EVT
} Custom_STM_Opcode_evt_t;

typedef struct
{
  uint8_t * pPayload;
  uint8_t   Length;
} Custom_STM_Data_t;

typedef struct
{
  Custom_STM_Opcode_evt_t       Custom_Evt_Opcode;
  Custom_STM_Data_t             DataTransfered;
  uint16_t                      ConnectionHandle;
  uint8_t                       ServiceInstance;
} Custom_STM_App_Notification_evt_t;

/* USER CODE BEGIN ET */
/* USER CODE END ET */

/* Exported constants --------------------------------------------------------*/
/* USER CODE BEGIN EC */
#define CUSTOM_STM_DATETIME_CHAR_SIZE (7U)
#define CUSTOM_STM_UINT32_CHAR_SIZE (4U)
#define CUSTOM_STM_STATUS_CHAR_SIZE (1U)
#define CUSTOM_STM_DATE_FORMAT_CHAR_SIZE (1U)
#define CUSTOM_STM_CALP_CHAR_SIZE (1U)
#define CUSTOM_STM_CALM_CHAR_SIZE (2U)
/* USER CODE END EC */

/* External variables --------------------------------------------------------*/
/* USER CODE BEGIN EV */
/* USER CODE END EV */

/* Exported macros -----------------------------------------------------------*/
/* USER CODE BEGIN EM */
/* USER CODE END EM */

/* Exported functions ------------------------------------------------------- */
void SVCCTL_InitCustomSvc(void);
// This function is defined in custop_app.c. 
void Custom_STM_App_Notification(Custom_STM_App_Notification_evt_t *pNotification);
tBleStatus Custom_STM_App_Update_Char(Custom_STM_Char_Opcode_t CharOpcode,  uint8_t const *pPayload);
/* USER CODE BEGIN EF */
/* USER CODE END EF */

#ifdef __cplusplus
}
#endif

#endif /*__CUSTOM_STM_H */

/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/
